# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
    ]
